name: Build

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        env GOOS=linux GOARCH=amd64 go build -o qrlabel_linux_amd64
        env GOOS=linux GOARCH=arm64 go build -o qrlabel_linux_arm64
        env GOOS=darwin GOARCH=amd64 go build -o qrlabel_macos_amd64
        env GOOS=darwin GOARCH=arm64 go build -o qrlabel_macos_arm64
        env GOOS=windows GOARCH=amd64 go build -o qrlabel_windows_amd64.exe
        env GOOS=windows GOARCH=arm64 go build -o qrlabel_windows_arm64.exe
        chmod +x qrlabel*
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: qrlabel*
